first draft of database ddl for collecting models
one-zero-eight/InNoHassle-Search pull request #2
Opened 2023-03-25 18:45 UTC by ruca905

2023-03-25 21:33 UTC, evermake commented
What are the advantages of creating the database comments?

2023-03-28 13:26 UTC, ruca905 commented
> What are the advantages of creating the database comments?

Easier to understand meaning behind the models in ide like Intellj IDEA and others

2023-03-28 13:52 UTC, evermake requested changes

2023-03-28 13:52 UTC, evermake commented on migrations/datastore/basic_models.sql
> +    constraint contact_phone_number_format check (phone ~ '^\+?[0-9]{1,3}-?[0-9]{3}-?[0-9]{3}-?[0-9]{4}$')
1. Regex and `phone` column length are mismatched, I think.
2. Will we store only Russian phone numbers? If so I think we should make stored format shorter and more strict.

2023-03-28 13:52 UTC, evermake commented on migrations/datastore/basic_models.sql
> +    id bigint primary key,
We should use `bigint GENERATED ALWAYS AS IDENTITY` for IDs (if we are going to use Postgres)

2023-04-07 19:20 UTC, evermake commented
PR conflicts with the project structure. I've created a new PR (see #3).

2023-04-07 19:20 UTC, closed without merging